name: entao_log
description: Dart log.
version: 1.2.0
repository: https://github.com/yangentao/entao_log
homepage: https://github.com/yangentao/entao_log

environment:
  sdk: ^3.8.0

dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
