name: entao_log
description: Dart log.
version: 1.2.7
repository: https://github.com/yangentao/entao_log
homepage: https://github.com/yangentao/entao_log

environment:
  sdk: ^3.5.0

dependencies:
  path: ^1.9.1
  println: ^1.0.4
  any_call: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
