name: entao_log
description: Dart log.
version: 2.0.0
repository: https://github.com/yangentao/entao_log
homepage: https://github.com/yangentao/entao_log

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  path: ^1.9.1
  entao_lint: ^1.0.1
  println: ^1.0.4


dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
